language: php

env:
  global:
    - UNIT_TESTS=0
    - STATIC_ANALYSIS=0
    - INTEGRATION_TESTS=0
    - CODE_COVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: 5.6.30
    - php: 7.0
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
    - php: 7.2
    - php: 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
